name: Gatsby Deploy

on:
  push:
    branches: master

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Config
        run: |
          git config --global user.email "shrey.viradiya.100@outlook.com"
          git config --global user.name "Shrey-Viradiya"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps
      - name: Deploy
        run: npm run deploy:ci